### ISSUE TITLE
Can't build `1.39.0` because `wasm32` arch is missed

### ISSUE THREAD

**Issue by catap** [thepowersgang/mrustc#234]
`wasm32` is heavy used inside sources, and attempt to build it fails with error:
```
  EXCEPTION: Unknown cfg value `target_arch` (="wasm32")
```

**Comment by thepowersgang** [comment]
This looks like it's coming from minicargo, can you provide more context for the error?
Minicargo has its own debug environment variable - `MINICARGO_DEBUG=Load Dependencies` might provide the context.

This error message should only show if mrustc failed to dump the `target_arch` variable - it's not because `wasm32` is unsupported.

**Comment by catap** [comment]
@thepowersgang it was a bit tricky to obtain, but I'll try to reproduce it with suggested debug.

**Comment by catap** [comment]
I can't reproduce an issue anymore.

Near the same moment I had a typo in `Cargo.toml` with line like `[target."cfg(not(any(target_os = \"windows\", target_os = \"wasm32\", target_os = \"macos\")))".dependencies.openssl]`. Maybe it was the root cause of this issue.
