### ISSUE TITLE
Question: Build compiler to wasm

### ISSUE THREAD

**Issue by pu0238** [thepowersgang/mrustc#282]
Is there an option to build this compiler to wasm and then use it on web page?

**Comment by bjorn3** [comment]
That is probably going to be hard. Mrustc requires an external compiler to compile the produced C files. Wasm doesn't support running external processes.

**Comment by pu0238** [comment]
wouldn't it be possible to do this by combining Mrustc with clang compiled to wasm?

**Comment by pu0238** [comment]
I care about compiling rust in the browser is the merger of these two programs possible?

**Comment by bjorn3** [comment]
I'm not sure you can combine mrustc, clang and lld together in a single process. There may be global state that would conflict. In any case it would require patches to all three. To clang and lld to rename the main function and to mrustc and clang to call the renamed main function instead of spawning a new process. Another thing is that getting clang to run on wasm requires a lot of patches. See https://github.com/binji/wasm-clang for an old example of this.

If you want to compile rust in the browser, it is probably going to be easier to use rustc instead. See for example https://github.com/rust-lang/miri/issues/722 for how to patch rustc to use cg_clif as statically linked backend (wasm requires static linking and cg_clif doesn't require any patching to run on wasm) and compile rustc to wasm. The only thing that is missing to produce working executables is a linker. It also can only compile to x86_64 and aarch64 as Cranelift doesn't have a wasm backend yet (https://github.com/bytecodealliance/wasmtime/issues/2566).

**Comment by pu0238** [comment]
Thank you for your help, I will try to build a miri. Maybe that's enough for my needs. I need to build rust in a browser to bpf format. If you have any information as to whether it is feasible or some advice I will be glad to accept it. :) Thank you for your time

**Comment by bjorn3** [comment]
Cg_clif doesn't support eBPF either. If you patch LLVM to run on wasm, it should be possible to patch rustc to run on wasm too. It probably isn't going to be easy though. Compiling on a server is almost definitively easier. There are also projects to run a linux vm using wasm. That is an option you could try too. It is of course slower than running directly in wasm though.

**Comment by pu0238** [comment]
I am considering virtual machine options in wasm, but I can't find the right one to compile rust. There is a project on which it is based, it has llvm adapted to work with clang and bpf (https://github.com/lithdew/alon). I wanted to create something similar, but based on rust, and I thought that this adaptation of the llvm would be helpful, however, until I can get a rustc, as I can forget about this solution and look for alternatives.

**Comment by pu0238** [comment]
compilation for bpf is done by llvm and adding necessary files to llvm rlib
