### ISSUE TITLE
Compiling a program written in Rust to C

### ISSUE THREAD

**Issue by sagnikbanerjee15** [thepowersgang/mrustc#294]
Hello,

I was wondering if the package (https://github.com/Minhyeok01/FCLQC) could be compiled into C. My entire intention is to speed up execution.

Thank you.

**Comment by bjorn3** [comment]
> My entire intention is to speed up execution.

Do you mean compared to when compiled with rustc? If so, it will likely be a regression to first translate it to C and then compile it compared to directly compiling. Rust doesn't have some kinds of UB that C has, working around this loses a bit of performance and C doesn't have some kinds of UB that Rust has, not using this UB during optimization loses a bit of performance too.

> I was wondering if the package (https://github.com/Minhyeok01/FCLQC) could be compiled into C.

You can try. In any case be aware that mrustc produces target specific code as it needs to evaluate conditional compilation attributes and memory layout computations before producing C code due to the way Rust works. As such you will have to either run mrustc as part of building your project or check in C code for every target you want to support.

**Comment by thepowersgang** [comment]
Re-compiling something written in rust into C won't make it faster - even more so if you use mrustc to do the compilation (mrustc's generated code is pretty bad - and gcc doesn't do the best job of cleaning it up).
