### ISSUE TITLE
Spare rules left after typecheck stabilised

### ISSUE THREAD

**Issue by dtolnay** [thepowersgang/mrustc#62]
```rust
struct Struct;

trait Trait {
    type Assoc;
}

impl Trait for Struct {
    type Assoc = Struct;
}

fn f<S>(_: &S) where S: Trait<Assoc = S> {}

fn g() {
    f(&Struct);
}
```

```
repro.rs:14: warning0:Spare Rule - &_/*3*/ := &::"repro-0_1_0"::Struct
repro.rs:14: warning0:Spare Rule - _/*3*/ = < _/*3*/ as ::"repro-0_1_0"::Trait >::Assoc
repro.rs:16: BUG:src/hir_typeck/expr_cs.cpp:6371: Spare rules left after typecheck stabilised
```

This is minimized from trying to compile calls to [this function](https://github.com/dtolnay/syn/blob/0.12.13/src/lit.rs#L884).

**Comment by thepowersgang** [comment]
Thanks for the minimal reproduction, it made confirming much easier :)
This is a much trickier issue than the macro ones, as typecheck is a huge mess of special cases and hacks around coercions.
Ideally, the second rule would be removed (because it doesn't add anything), but the typecheck code doesn't know that, so assumes that `_/*3*/` might not be `Struct`

(Notes on fixes follow)
Potential solution: before attempting inference defaults, try ivar possibilities without honouring. the 'disable' flag.

**Comment by thepowersgang** [comment]
As the above commit implies, it worked.

Hopefully the fix works for the non-reduced case.

**Comment by dtolnay** [comment]
Thanks! Yes that fixed the real case.
